#index:
#    path: /
#    controller: App\Controller\DefaultController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController::create
    methods: POST

app.swagger_ui:
    path: /document
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# config/routes.yaml
app.swagger:
    path: /document.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }