nelmio_api_doc:
    documentation:
        info:
            title: Lokalise Assignment
            description: Technical test - Rodrigo de Almeida
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/document$) # Accepts routes under /api except /api/doc